services:
  app:
    build: .
    container_name: "g07_app"
    ports:
      - "3007:3000"
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
      - course_proxy

  db:
    image: mysql:8.0
    container_name: "g07_db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: room_booking
      MYSQL_USER: room_user
      MYSQL_PASSWORD: room_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: bridge
  course_proxy:
    external: true
